### ISSUE TITLE
images not always laid out correctly on initial page load

### ISSUE THREAD

**Issue by cheshire137** [ionelmc/jquery-gp-gallery#1]
When a gallery page first loads, the images aren't always sized correctly.  Reloading the page usually fixes this; I'm in Chrome.  I did some debugging and `item.original_height` was set to 0 sometimes.  I think this is due to Webkit browsers setting height and width after an image is loaded; see http://stackoverflow.com/questions/318630/get-real-image-width-and-height-with-javascript-in-safari-chrome  I ended up setting a `width` and `height` attribute on my images, then adding this to jquery-gp-gallery.js within `$container.find(selector).each(function() {` just after `var item` is defined but before `item.scale` is calculated:

``` javascript
if (0 == item.original_width) {
    var widthAttr = $pic.attr('width');
    if (typeof widthAttr !== 'undefined' && widthAttr !== false) {
        item.original_width = widthAttr;
    }
}
if (0 == item.original_height) {
    var heightAttr = $pic.attr('height');
    if (typeof heightAttr !== 'undefined' && heightAttr !== false) {
        item.original_height = heightAttr;
    }
}
```

This fixed the problem so that `item.original_width` and `item.original_height` are always set correctly, so the scale, scaled width, and scaled height are correct on initial page load.

**Comment by ionelmc** [comment]
380acdc2c124846a41b22bae3a8fb3db1bd93514 should fix this problem
